### ISSUE TITLE
Package no longer activates due to API deprecations

### ISSUE THREAD

**Issue by cliffrowley** [fotanus/rails-navigation#5]
I notice this package hasn't been updated since 2014. I would still like to use it, and if you no longer wish to maintain it please add me as a contributor and I will get it updated ASAP. Thanks.

**Comment by fotanus** [comment]
Hey @cliffrowley, striking code is no more and I couldn't move this git repo because otherwise it fails to download from inside atom. Not sure how are things now, but feel free to do whatever you think it is right with the package, since I can't maintain it any longer!

Just add you as commiter.
